train_file:  ['../dataset/RSTPReid/processed_data/train.json']
val_file: '../dataset/RSTPReid/processed_data/val.json'
test_file: '../dataset/RSTPReid/processed_data/test.json'
train_image_root: '../dataset/RSTPReid/imgs'
val_image_root: '../dataset/RSTPReid/imgs'
test_image_root: '../dataset/RSTPReid/imgs'

bert_config: 'configs/config_bert.json'

max_words: 50
image_res: 384
batch_size_train: 13
batch_size_test: 64

mlm_probability: 0.15
weak_pos_pair_probability: 0.1
mrtd_mask_probability: 0.3

queue_size: 65536
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128

alpha: 0.4
warm_up: True

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02, lr_custm: 1e-4}
schedular: {sched: cosine, lr: 1e-5, epochs: 30, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}

eval_epoch: 0

weights:
  - 0.5
  - 1
  - 1
  - 0.5
  - 0.5
